//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RavenDBClusterBuilderExtensions
    {
        [AspireExportIgnore(Reason = "The options callback is not supported by ATS.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> PublishAsRavenDBCluster(this ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> builder, System.Action<CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes.RavenDBClusterOptions> configure) { throw null; }
    }

    public static partial class RavenDBKubernetesClientCertificateExtensions
    {
        [AspireExport("withRavenDBDatabaseClientCertificateSecret", MethodName = "withRavenDBClientCertificateSecret")]
        public static ApplicationModel.IResourceBuilder<T> WithRavenDBClientCertificateSecret<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBDatabaseResource> database, string secretName, string? certificateAuthoritySecret = null)
            where T : ApplicationModel.IComputeResource { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes
{
    public sealed partial class RavenDBClusterOptions
    {
        public string? Domain { get { throw null; } set { } }

        public string? Image { get { throw null; } set { } }

        public string IngressClassName { get { throw null; } set { } }

        public string? LicenseSecretName { get { throw null; } set { } }

        public int Nodes { get { throw null; } set { } }

        public string? StorageClassName { get { throw null; } set { } }

        public string StorageSize { get { throw null; } set { } }

        public RavenDBClusterOptions WithCertificates(string serverCertificateSecret, string clientCertificateSecret, string? certificateAuthoritySecret = null) { throw null; }

        public RavenDBClusterOptions WithLetsEncrypt(string email, string clientCertificateSecret) { throw null; }
    }
}