//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RavenDBClusterBuilderExtensions
    {
        [AspireExport(RunSyncOnBackgroundThread = true)]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> PublishAsRavenDBCluster(this ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> builder, System.Action<CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes.RavenDBClusterOptions> configure) { throw null; }
    }

    public static partial class RavenDBKubernetesClientCertificateExtensions
    {
        [AspireExportIgnore(Reason = "Polyglot app hosts pass the server: ATS allows one export per member name and target type.")]
        public static ApplicationModel.IResourceBuilder<T> WithRavenDBClientCertificateSecret<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBDatabaseResource> database, string secretName, string? certificateAuthoritySecret = null)
            where T : ApplicationModel.IComputeResource { throw null; }

        [AspireExport("withRavenDBServerClientCertificateSecret", MethodName = "withRavenDBClientCertificateSecret")]
        public static ApplicationModel.IResourceBuilder<T> WithRavenDBClientCertificateSecret<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> server, string secretName, string? certificateAuthoritySecret = null)
            where T : ApplicationModel.IComputeResource { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes
{
    [global::Aspire.Hosting.AspireExport(ExposeProperties = true, ExposeMethods = true)]
    public sealed partial class RavenDBClusterOptions
    {
        public string? Domain { get { throw null; } set { } }

        public string? Image { get { throw null; } set { } }

        public RavenDBIngressController IngressController { get { throw null; } set { } }

        public string? LicenseSecretName { get { throw null; } set { } }

        public int Nodes { get { throw null; } set { } }

        public string? StorageClassName { get { throw null; } set { } }

        public string StorageSize { get { throw null; } set { } }

        public RavenDBClusterOptions WithCertificates(string serverCertificateSecret, string clientCertificateSecret, string? certificateAuthoritySecret = null) { throw null; }

        public RavenDBClusterOptions WithLetsEncrypt(string email, string clientCertificateSecret) { throw null; }
    }

    public enum RavenDBIngressController
    {
        Traefik = 0,
        HAProxy = 1,
        Nginx = 2
    }
}