<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>33f52d1f-f724-4144-91d3-c8c62648ea00</UserSecretsId>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes\CommunityToolkit.Aspire.Hosting.RavenDB.Kubernetes.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
