//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RavenDBCloudBuilderExtensions
    {
        [AspireExport(RunSyncOnBackgroundThread = true)]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> PublishAsRavenDBCloud(this ApplicationModel.IResourceBuilder<ApplicationModel.RavenDBServerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> apiKey, System.Action<CommunityToolkit.Aspire.Hosting.RavenDB.Cloud.RavenDBCloudOptions>? configure = null) { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.RavenDB.Cloud
{
    [global::Aspire.Hosting.AspireExport(ExposeProperties = true, ExposeMethods = true)]
    public sealed partial class RavenDBCloudOptions
    {
        public System.Collections.Generic.IList<string> AllowedIps { get { throw null; } }

        public string ApiEndpoint { get { throw null; } set { } }

        public int? DiskSizeInGb { get { throw null; } set { } }

        public string? InstanceType { get { throw null; } set { } }

        public string? ProductName { get { throw null; } set { } }

        public RavenDBCloudProvider Provider { get { throw null; } set { } }

        [global::Aspire.Hosting.AspireExportIgnore(Reason = "A TimeSpan reaches polyglot app hosts as a number without a unit.")]
        public System.TimeSpan ProvisioningTimeout { get { throw null; } set { } }

        public string? Region { get { throw null; } set { } }

        public string? ReleaseChannel { get { throw null; } set { } }

        public RavenDBCloudStorageType StorageType { get { throw null; } set { } }

        public string? Subdomain { get { throw null; } set { } }

        public bool TerminateOnDestroy { get { throw null; } set { } }

        public RavenDBCloudTier Tier { get { throw null; } set { } }

        public RavenDBCloudOptions WithAllowedIps(params string[] allowedIps) { throw null; }
    }

    public enum RavenDBCloudProvider
    {
        Aws = 0,
        Azure = 1,
        Gcp = 2
    }

    public enum RavenDBCloudStorageType
    {
        SsdStandard = 0,
        SsdPremium = 1
    }

    public enum RavenDBCloudTier
    {
        Free = 0,
        Development = 1,
        Production = 2
    }
}