<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>4fcd02ee-860a-4d4d-9219-7e37faa3c05a</UserSecretsId>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.RavenDB.Cloud\CommunityToolkit.Aspire.Hosting.RavenDB.Cloud.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
